apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-redis-secret-creator
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "list", "watch"] # include other necessary verbs
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["argocd-redis"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]