apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-redis-secret-init-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-redis-secret-init
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-redis-secret-creator
  apiGroup: rbac.authorization.k8s.io