name: ci

on:
  push:
    paths: 
        - src/**
    branches:
        - main


jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.var.outputs.IMAGE_TAGS }}
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set short git commit SHA
        id: var
        run: | 
             IMAGE_TAGS="${GITHUB_SHA::7}"
             echo "IMAGE_TAGS=$IMAGE_TAGS" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: myprac/python-app:${{ steps.var.outputs.IMAGE_TAGS }}
  
  cd:
    runs-on: arc-runner-set
    needs: ci
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.tag}}
          #pip install yq
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version
          yq -Yi '.image.tag = "${{needs.ci.outputs.tag}}"' charts/python-app/values.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
              message: 'Updates values.yaml with commit ${{needs.ci.outputs.tag}}'
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: Argocd App and Sync
        run: |
         argocd login argocd-server.argocd --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
         argocd app sync python-app